# Generated by Django 2.2.7 on 2019-11-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('picture_url', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('registered_time', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('auth_status', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('fcm_token', models.CharField(max_length=1000)),
            ],
        ),
    ]
